services:
  mysql:
    image: mysql:8.0
    container_name: whiteboard-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rajk123#
      MYSQL_DATABASE: whiteboard
    ports:
      - "3307:3306" # changed host port to 3307 to avoid conflicts
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: live-whiteboard-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:8081" # host:container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/whiteboard
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Rajk123#
      SERVER_PORT: 8081 # ensures Spring Boot runs on 8081

volumes:
  mysql_data:
